#! /bin/sh -e

homebrewDir="${APP_BUNDLE:?}/Contents/homebrew"

export PATH="${PATH:?}:${homebrewDir:?}/bin"
export DYLD_FALLBACK_LIBRARY_PATH="${DYLD_FALLBACK_LIBRARY_PATH+${DYLD_FALLBACK_LIBRARY_PATH}:}${homebrewDir:?}/lib"
