#! /bin/sh -xe

bn=$(basename "$0")
wd=$(dirname "$0")

PATH="$PATH":~/homebrew/bin:"${wd:?}"
domain="com.grigorye.SimulatorRecorder"

#

customRecordingsDir=$(defaults read "${domain:?}" recordingsDir || true)
recordingsDir=${customRecordingsDir:-"${HOME:?}/Simulator Recordings"}

customVideoNameFormat=$(defaults read "${domain:?}" videoNameFormat || true)
if [ z"${customVideoNameFormat}" == "z" ]
then
	videoName="$(timestamp) $(simulatorName)"
else
	videoName=$(eval echo ${customVideoNameFormat:?})
fi

#

tmpdir=$(mktemp -d "${TMPDIR:?}"/"${bn:?}".XXXXX)

rawVideo="${TMPDIR:?}/simvideo.mov"
convertedVideo="${recordingsDir:?}/${videoName:?}.m4v"

mkdir -p "${recordingsDir:?}"

xcrun simctl io booted recordVideo "${rawVideo:?}"
ffmpeg -v -8 -i "${rawVideo:?}" "${convertedVideo:?}"

open -R "${convertedVideo:?}"

rm "${rawVideo:?}"
rmdir "${tmpdir:?}"
