#! /bin/sh -xe

bn=$(basename "$0")
wd=$(dirname "$0")

PATH="$PATH":~/homebrew/bin:"${wd:?}"
domain="com.grigorye.SimulatorRecorder"
registrationDomain="${wd:?}/Defaults"

#

defaultFor() {
	type="${1:?}"; shift
	key="${1:?}"; shift
	customValue=$(defaults read "${domain:?}" "${key:?}" || true)
	readType=$(defaults read-type "${registrationDomain:?}" "${key:?}")
	[ "Type is ${type:?}" = "${readType:?}" ]
	value=${customValue:-$(defaults read "${registrationDomain:?}" "${key:?}")}
	echo "${value:?}"
}

#

recordingsDir=$(eval echo "$(defaultFor string "recordingsDir")")
revealInFinder=$(defaultFor boolean "revealInFinder")
videoNameFormat=$(defaultFor string "videoNameFormat")

#

tmpdir=$(mktemp -d "${TMPDIR:?}"/"${bn:?}".XXXXX)

videoName=$(eval echo "${videoNameFormat:?}")
rawVideo="${tmpdir:?}/simvideo.mov"
convertedVideo="${recordingsDir:?}/${videoName:?}.m4v"

mkdir -p "${recordingsDir:?}"

xcrun simctl io booted recordVideo "${rawVideo:?}"
ffmpeg -v -8 -i "${rawVideo:?}" "${convertedVideo:?}"

if [ "${revealInFinder:?}" = 1 ]
then
	open -R "${convertedVideo:?}"
fi

rm "${rawVideo:?}"
rmdir "${tmpdir:?}"
