#! /bin/sh -xe

bn=$(basename "$0")
wd=$(dirname "$0")

PATH="$PATH":~/homebrew/bin:"${wd:?}"
domain="com.grigorye.SimulatorRecorder"
registrationDomain="${wd:?}/Defaults"

#

defaultFor() {
	type="${1:?}"; shift
	key="${1:?}"; shift
	customValue=$(defaults read "${domain:?}" "${key:?}" || true)
	readType=$(defaults read-type "${registrationDomain:?}" "${key:?}")
	[ "Type is ${type:?}" = "${readType:?}" ]
	value=${customValue:-$(defaults read "${registrationDomain:?}" "${key:?}")}
	echo "${value:?}"
}

#

recordingsDir=$(eval echo "$(defaultFor string "recordingsDir")")
revealInFinder=$(defaultFor boolean "revealInFinder")
videoNameFormatEscaped=$(defaultFor string "videoNameFormat")
videoNameFormat=$(echo "[\"${videoNameFormatEscaped:?}\"]" | python -c 'import json, sys; sys.stdout.write(json.load(sys.stdin)[0].encode("utf-8"))')

timestamp=$(timestamp)
simulatorName=$(simulatorName)
timestampFormat="%Y-%m-%d_%H%M%S"
timestamp=$(date +"${timestampFormat:?}")

date=$(date -j -f "${timestampFormat:?}" "${timestamp:?}" +"%Y-%m-%d")
time=$(date -j -f "${timestampFormat:?}" "${timestamp:?}" +"%H.%M.%S")
device=$(echo ${simulatorName:?} | sed 's/^\(.*\) - \(.*\)$/\1/')
version=$(echo ${simulatorName:?} | sed 's/^\(.*\) - \(.*\)$/\2/')

#

tmpdir=$(mktemp -d "${TMPDIR:?}"/"${bn:?}".XXXXX)

videoName=$(eval echo "${videoNameFormat:?}")
rawVideo="${tmpdir:?}/simvideo.264"
convertedVideo="${recordingsDir:?}/${videoName:?}.m4v"

mkdir -p "${recordingsDir:?}"

xcrun simctl io booted recordVideo --type='h264' "${rawVideo:?}"
ls -l "${rawVideo:?}"
ffmpeg -v -8 -i "${rawVideo:?}" "${convertedVideo:?}"

if [ "${revealInFinder:?}" = 1 ]
then
	open -R "${convertedVideo:?}"
fi

rm "${rawVideo:?}"
rmdir "${tmpdir:?}"
