#! /bin/sh -e

set -o pipefail

simulatorPID=$(pgrep -f '^\/.*\/MacOS\/Simulator')
export DEVELOPER_DIR=$(dirname $(dirname $(dirname $(dirname $(dirname $(ps -o comm ${simulatorPID:?} | tail -1 | head -1))))))

xcrun simctl list -j |
    jq -r '[.devices|to_entries|.[]|{os_ver: .key, device_name: (.value|to_entries|.[]|.value|select(.state == "Booted")|.name)}]|.[0]|(.device_name // error("no-Booted")) + " - " + .os_ver'
