stages:
  - build

build_project:
  stage: build
  script:
    - formulaName="simulator-recorder"
    - packageName="${CI_PROJECT_NAME:?}"
    - ./Pods/GEContinuousIntegration/Scripts/build-gitlab-cmd "$PWD/build" "${packageName:?}" "${formulaName:?}" XC_FABRIC_BUILD_SECRET="${XC_FABRIC_BUILD_SECRET:?}"
  artifacts:
    paths:
      - build/*.pkg
      - build/*.dmg
      - build/Formula/*.rb
      - build/*.log
  tags:
    - xcode-10
    - macos
