stages:
  - build

build_project:
  stage: build
  script:
    - packageName="${CI_PROJECT_NAME:?}"
    - ./build-gitlab-cmd "$PWD/build" "${packageName:?}.pkg"
  artifacts:
    paths:
      - build/*.pkg
  tags:
    - xcode-10
    - macos
