stages:
  - build

build_project:
  stage: build
  script:
    - packageName="${CI_PROJECT_NAME:?}"
    - ./build-gitlab "$PWD/build/${packageName:?}.pkg" GE_DERIVED_DATA_PATH="$PWD"/build/DerivedData DSTROOT="$PWD"/build/"${packageName:?}".dst
  artifacts:
    paths:
      - build/DerivedData/*.pkg
  tags:
    - xcode-10
    - macos
