osx_image: xcode9.4
language: swift
before_install:
  - bundle install
  - bundle exec pod repo update
script:
  - packageName="SimulatorRecorder"
  - formulaName="simulator-recorder"
  - export GE_DISABLE_XCPRETTY=1
  - ./Pods/GEContinuousIntegration/Scripts/build-gitlab-cmd "$PWD/build" "${packageName:?}" "${formulaName:?}"
