#! /usr/bin/env -i /bin/sh -ex

pkg="${1:?}"; shift

export "${@}"

bn=$(basename "$0")

eval "$(/usr/libexec/path_helper)"

workspaces=(*.xcworkspace)
workspace="${workspaces[0]}"
projectName="${workspace%.*}"

tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/${bn:?}.XXXXX")

installDir="${DSTROOT:-${tmpdir:?}/Install}"
derivedDataPath="${GE_DERIVED_DATA_PATH:-${tmpdir:?}/DerivedData}"

buildProject() {
    xcodebuild \
        -workspace "${workspace:?}" \
        -scheme "${projectName:?}" \
        "${@}"
}

buildProject \
    -derivedDataPath "${derivedDataPath:?}" \
    install \
    DSTROOT="${installDir:?}" \
    "${@}"

productDefinitionPlist=$(buildProject -showBuildSettings | awk '/.* PRODUCT_DEFINITION_PLIST = (.*)/ {print $3}')

productbuild \
    --product "${projectName:?}"/"${productDefinitionPlist:?}" \
    --root "${installDir:?}" \
    "${pkg:?}"
