#! /bin/sh -xe

set -o pipefail

formulaDir="build/Formula"
formula="${formulaDir:?}/simulator-recorder.rb"
dmg="build/SimulatorRecorder.dmg"

test -d "${formulaDir:?}" || mkdir "${formulaDir:?}"

cat > "${formula:?}" <<END
cask 'simulator-recorder' do
  version '$(defaults read "$PWD"/build/SimulatorRecorder.dst/Applications/SimulatorRecorder.app/Contents/Info CFBundleVersion)'
  sha256 '$(shasum -a 256 "${dmg:?}" | cut -d ' ' -f 1)'

  url 'https://gitlab.com/grigorye/SimulatorRecorder/-/jobs/${CI_JOB_ID:?}/artifacts/raw/build/SimulatorRecorder.dmg'
  name 'Simulator Recorder'
  homepage 'https://gitlab.com/grigorye/SimulatorRecorder'

  app 'SimulatorRecorder.app'
end
END
