#! /bin/sh -xe

set -o pipefail

pkg="${1:?}"; shift

bundle install
bundle exec pod repo update
bundle exec pod install

./build-pkg \
    "${pkg:?}" \
    ${DEVELOPER_DIR:+DEVELOPER_DIR="${DEVELOPER_DIR}"} \
    "${@}" \
    | bundle exec xcpretty
