#! /bin/sh -xe

xcodeproj="${1:?}"

wd=$(dirname "$0")

target=$(basename ${xcodeproj:?}|sed 's/.xcodeproj//')
"${wd:?}"/CreateOrUpdateEmbedSourcesBuildPhase "${xcodeproj:?}" "${target:?}" 'Sources/$(TARGET_NAME)'
