#! /bin/sh -e

#  IntegrateAppsee
#  RSSReader
#
#  Created by Grigory Entin on 24.01.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

[ "${APPSEE_ENABLED:?}" == "YES" ] || exit 0
"${GE_XCODE_SCRIPTS:?}"/VersionIsClean || exit 0

./Appsee-upload_symbols.sh "${XC_APPSEE_API_KEY:?}"

infoPlistWOExt=$(echo "${INFOPLIST_PATH:?}" | sed 's/.plist$//')
infoPlistDefaultsDomain="${CONFIGURATION_BUILD_DIR:?}/${infoPlistWOExt:?}"
defaults write "${infoPlistDefaultsDomain:?}" appseeAPIKey -string "${XC_APPSEE_API_KEY:?}"
