#!/bin/sh -xe

#  PackageApplication
#  RSSReader
#
#  Created by Grigory Entin on 31.01.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

app="${TARGET_BUILD_DIR:?}/${FULL_PRODUCT_NAME:?}"
ipa="${TARGET_BUILD_DIR:?}/${PRODUCT_NAME:?}.ipa"

xcodebuild -exportArchive -archivePath "${ARCHIVE_PATH:?}" -exportPath "${ipa:?}"
