#! /bin/sh -ex

#  UploadToFabric
#  RSSReader
#
#  Created by Grigory Entin on 11.02.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

[ "${XC_UPLOAD_TO_FABRIC_ENABLED:?}" == "YES" ] || exit 0
"${GE_XCODE_SCRIPTS:?}"/VersionIsClean || exit 0

ipa="${TARGET_BUILD_DIR:?}/${PRODUCT_NAME:?}.ipa"
"${PODS_ROOT:?}"/Crashlytics/submit "${XC_FABRIC_API_KEY:?}" "${XC_FABRIC_BUILD_SECRET:?}" -ipaPath "${ipa:?}"
