#! /bin/bash -ex

#  XCBundleBrewPackages
#  SimulatorRecorder
#
#  Created by Grigory Entin on 22/07/2018.
#  Copyright © 2018 Grigory Entin. All rights reserved.

dn=$(dirname "$0")

"$dn/XCInstallBrewPackages"
"$dn/XCPreprocessBrewPackages"
"$dn/XCRsyncPreprocessedBrewPackages"
