#! /bin/bash -ex

#  XCPreprocessBrewPackages
#  SimulatorRecorder
#
#  Created by Grigory Entin on 22/07/2018.
#  Copyright © 2018 Grigory Entin. All rights reserved.

dn=$(dirname "$0")

homebrewDir="${GE_HOST_HOMEBREW_DIR:?}"

chmod -R +w "${homebrewDir:?}"
"${dn:?}"/update-homebrew-bundle-lib-names.rb -v "${homebrewDir:?}"
