#! /bin/sh -e

#  IntegrateFabric
#  RSSReader
#
#  Created by Grigory Entin on 24.01.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

[ "${CRASHLYTICS_ENABLED:?}" == "YES" ] || exit 0
"${GE_XCODE_SCRIPTS:?}"/VersionIsClean || exit 0

"${PODS_ROOT:?}"/Fabric/run "${XC_FABRIC_API_KEY:?}" "${XC_FABRIC_BUILD_SECRET:?}"

# find "${CONFIGURATION_BUILD_DIR:?}" -name "*.dSYM" | xargs -I {} "${PODS_ROOT:?}"/../Tools/Crashlytics/uploadSymbols "${XC_FABRIC_API_KEY:?}" ios {}
